### ISSUE TITLE
i3环境运行不了

### ISSUE THREAD

**Issue by newyorkthink** [openSUSE-zh/wps-office-appimage#1]
![image](https://user-images.githubusercontent.com/87791643/209782539-f485efb9-de60-424c-8c78-dda053015b9d.png)

![image](https://user-images.githubusercontent.com/87791643/209782568-ba21a90f-1117-4cd6-8f04-83ab7eefa97f.png)

只显示这些，点不了

**Comment by marguerite** [comment]
是你的 glibc 版本太低了，跟 i3 没有关系。

我弄了一个最新版的，是用 leap 15.1 编译的 wps-launcher，你可以再试试。
